Add CISA Exploited Risk Score Comparison Script
KennaSecurity/All_Samples pull request #155
Opened 2022-06-10 22:38 UTC by jaredkalmus

Jerry wrote some code to analyze the CISA Known Exploited CVEs' Kenna Risk Scores a few months ago. This script allows Kenna VI+ customers to perform similar analysis.

2022-06-10 23:00 UTC, rick-kenna requested changes

2022-06-11 16:32 UTC, jgamblin commented on CISA Exploited CVE Risk Score Comparison/cisa_risk_scores.py
> +cisa_df = cisa_df
It reads in the CSV directly from the CISA website into a dataframe without having to do a secondary call.

2022-06-11 17:46 UTC, jgamblin commented on CISA Exploited CVE Risk Score Comparison/cisa_risk_scores.py
> +cves
It takes all the CVEID columns out of the CISA dataframe and turns it into a python list to be able to pass to the Kenna API for sanity verification it also prints them in the terminal.

2022-06-11 17:48 UTC, jgamblin commented on CISA Exploited CVE Risk Score Comparison/cisa_risk_scores.py
> +cves
The first two lines cleans the CSV data as they sometimes include u200b (ZERO WIDTH SPACE) which will mess up any future API calls.

2022-06-13 16:45 UTC, rick-kenna commented on CISA Exploited CVE Risk Score Comparison/cisa_risk_scores.py
> +cves
Thanks, I see the to_list().  I was confused by line 12, just `cves`.

2022-06-13 18:53 UTC, jaredkalmus commented on CISA Exploited CVE Risk Score Comparison/cisa_risk_scores.py
> +cves
I don't think line 12 has any functionality here, right? The code was originally in a Jupyter notebook so that line might have just been used to visualize the list of CVEs for a sanity check while stepping through the notebook? If so it probably makes sense to remove it for this script

2022-06-13 19:59 UTC, jaredkalmus commented on CISA Exploited CVE Risk Score Comparison/cisa_risk_scores.py
> +cves
Removed the line and it didn't seem to reduce any functionality

2022-06-13 21:58 UTC, rick-kenna approved these changes

2022-06-13 22:12 UTC, merged