Initial checkin of csv_to_kdi.py
KennaSecurity/All_Samples pull request #170
Opened 2022-11-04 22:12 UTC by rick-kenna

Still testing, but it is pretty complete.  It is based of of `csv_KDI_json.rb` with some enhancements in argument processing.

If you think logging would be nice, please speak up.

I found a "main locator" bug.

2022-11-10 23:28 UTC, jaredkalmus requested changes
Output is not matching between the Ruby script and Python script. My metafile has tag columns and tag prefixes defined, however these columns are not present in my data source file. When I run the Ruby script the non-matched tags are not added to the JSON, while the Python script includes the tags and tag prefixes from the metadata file, even though the data source file does not have column matches for the tag columns provided in the metadata file.
[testing.zip](https://github.com/KennaSecurity/All_Samples/files/9985285/testing.zip)

2022-11-23 22:21 UTC, victorz1982 approved these changes
There are 2 non-blocking comments

2022-11-23 22:21 UTC, victorz1982 commented on KDI Importer/README.md
>  ```
```suggestion
```ruby
```
See [Syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) in markdown docs

2022-11-23 22:21 UTC, victorz1982 commented on KDI Importer/README.md
> +```
```suggestion
```python
```
Similar to the other suggestion

2022-11-28 21:18 UTC, jaredkalmus approved these changes

2022-11-29 22:02 UTC, merged